export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_PENDING = 'REQUESTS_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUESTS_ROBOTS_SUCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUESTS_ROBOTS_FAILED';